### ISSUE TITLE
Generar el wireframe para teléfonos inteligentes

### ISSUE THREAD

**Issue by axeliodiaz** [CanaimaGNULinux/canaimagnulinux.mockup#3]
Se debe diseñar los wireframe para dispositivos móviles utilizando la herramenta usada para el diseño principal del sitio: http://canaimagnulinux.mybalsamiq.com/projects/sitiowebprincipal/Inicio

**Comment by macagua** [comment]
@eliezerfot123 en gran medida :)

**Comment by macagua** [comment]
@Axelio entonces se puede cerrar este issue ?

cc @eliezerfot123 , @dehivix

**Comment by axeliodiaz** [comment]
@eliezerfot123 
Acá está el diseño mobil: https://canaimagnulinux.mybalsamiq.com/projects/sitiowebmovil
Y acá el desktop: https://canaimagnulinux.mybalsamiq.com/projects/sitiowebprincipal

No sé si sea necesario generar un wireframe con los diseños de tabletas, no sé qué opinen uds si sea o no necesario (¿?)

¿Podría maxudes corroborar si le parece correcta la distribución de contenidos del diseño mobil?
