### ISSUE TITLE
Estatus del la rama develop

### ISSUE THREAD

**Issue by macagua** [CanaimaGNULinux/canaimagnulinux.mockup#8]
@goidor puedes explicarnos para que trababas en esta rama y su utilidad? 

Se debe fusionar? a cual rama?

Si fue el caso que ya se fusiono se puede borrar esta rama?

Estamos unificando esfuerzos para implementarlos en los sitios Web

**Comment by Axelio** [comment]
La idea de esta rama es mostrar en modo html el cómo iba quedando lo que se iba subiendo tal como si fuera la página en producción. Debería verse en <usuario>.github.io/<rama> o lo que sería: canaimagnulinux.gitub.io/canaimagnulinux.mockup pero al parecer está deshabilitada, pero se puede reactivar sin rollos...

**Comment by macagua** [comment]
@Axelio entonces no hay problema que haga merge de esta rama a master ?

**Comment by Axelio** [comment]
Ninguno, a hacer merge a Master y luego de master a gh-pages

**Comment by macagua** [comment]
@Axelio Merge a la master en el commit 323fbd0

**Comment by macagua** [comment]
@Axelio Merge de la master al gh-pages con el commit df7a6a7
